cmake_minimum_required(VERSION 2.7)

macro(print_all_variables)
    message(STATUS "print_all_variables------------------------------------------{")
    get_cmake_property(_variableNames VARIABLES)
    foreach (_variableName ${_variableNames})
        message(STATUS "${_variableName}=${${_variableName}}")
    endforeach()
    message(STATUS "print_all_variables------------------------------------------}")
endmacro()

macro(print_var var_name)
	message(STATUS "${var_name}=${${var_name}}")
endmacro()

function(prepend_filepath files_var_name prefix)
   	set(prepended_files "")
	set(input_files ${${files_var_name}})
    foreach(file ${input_files})
    	list(APPEND prepended_files "${prefix}/${file}")
   	endforeach(file)
    set(${files_var_name} "${prepended_files}" PARENT_SCOPE)
endfunction(prepend_filepath)

macro(prepend_listdir)
	foreach(var_name ${ARGN})
		prepend_filepath(${var_name} ${CMAKE_CURRENT_LIST_DIR})
	endforeach(var_name)
endmacro(prepend_listdir)

set(debug_output ON)
set(debug_output_var ON)
set(debug_output_sourcevar OFF)

function(debug_print str)
	if(debug_output)
		message(STATUS ${str})
	endif(debug_output)
endfunction(debug_print)

macro(debug_print_var var_name)
	if(debug_output_var)
		print_var(${var_name})
	endif(debug_output_var)
endMacro(debug_print_var)

macro(debug_print_sourcevar var_name)
	if(debug_output_sourcevar)
		print_var(${var_name})
	endif(debug_output_sourcevar)
endMacro(debug_print_sourcevar)
