//
//  CastleDef.h
//  CastleSim
//
//  Created by Alex Saalberg on 4/25/18.
//

#ifndef CastleDef_h
#define CastleDef_h

#define CASTLE_VOXELTYPE uint8_t

enum BlockTypes { BLOCK_AIR=0, BLOCK_GRASS=1, BLOCK_STONE=2, BLOCK_YELLOW=3, BLOCK_ORANGE=4, BLOCK_RED=5, BLOCK_VIOLET=6, BLOCK_BLUE=7, BLOCK_BLACK=8, BLOCK_WHITE=9, BLOCK_REDOUTLINE=10};

enum SelectedBlock { BLOCK1 = BLOCK_GRASS, BLOCK2 = BLOCK_STONE, BLOCK3 = BLOCK_YELLOW, BLOCK4 = BLOCK_ORANGE, BLOCK5=BLOCK_RED, BLOCK6=BLOCK_VIOLET, BLOCK7=BLOCK_BLUE, BLOCK8=BLOCK_BLACK, BLOCK9=BLOCK_WHITE, BLOCK0=BLOCK_AIR};

#endif /* CastleDef_h */
